### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by develVannessa** [arielmission-space/ExoSim2-public#1]
In the documentation page, FAQs : What if ExoSim cannot find the required packages?
pip install -r requirements.txt 
--> unfortunately this file does not exist on the git repository 
Please add the up to date files

THX

**Comment by LorenzoMugnai** [comment]
Fixed in [commit b12328f](https://github.com/arielmission-space/ExoSim2-public/commit/b12328f3abcb308becf87816d6a082395c1f0447#diff-2e6ffde6675bcefc4c7dc972bc5de16884d19f6a3732f0df11345712d8e9f344)

Thanks
